# Generated by Django 5.0.1 on 2024-01-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='marks1',
            field=models.IntegerField(default=0),
        ),
    ]
